#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_stat:
  path: /stat
  controller: App\Controller\ServiceController::stats
app_offre_search:
  path: '/search-offres'
  controller: 'App\Controller\UserController::searchOffres'
bank_get_qr_code:
  path: '/bank/account/{Id}/qrcode'
  controller: 'App\Controller\ComptebancaireController::getQrCodeForAccount'
  methods: ['GET']
  requirements:
    Id: '\d+'

exporter_proprietaire_pdf:
  path: '/proprietaire/{id}/exporter-pdf'
  controller: 'App\Controller\ComptebancaireController::exporterPdf'